basePath: /
definitions:
  dto.CreateTodoDTO:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  dto.CreateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  dto.UpdateTodoDTO:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  dto.UpdateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  entity.Todo:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  entity.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  error.Response:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple API.
  title: GoSimpleAPI
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Hello world
      tags:
      - Default
  /todo:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a list of Todo items, optionally filtered
        by a search query.
      parameters:
      - description: Search query to filter Todo items
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of Todo items
          schema:
            items:
              $ref: '#/definitions/entity.Todo'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Get a list of Todo items
      tags:
      - Todo
    post:
      consumes:
      - application/json
      description: This endpoint allows the user to create a new Todo item.
      parameters:
      - description: Todo Data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTodoDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created Todo item
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/error.Response'
      summary: Create a new Todo item
      tags:
      - Todo
  /todo/{id}:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a Todo item based on the provided ID.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Todo item
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/error.Response'
        "404":
          description: Todo not found
          schema:
            $ref: '#/definitions/error.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Get a Todo item by ID
      tags:
      - Todo
    put:
      consumes:
      - application/json
      description: This endpoint allows the user to update an existing Todo item by
        ID.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Todo Data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTodoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated Todo item
          schema:
            $ref: '#/definitions/entity.Todo'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/error.Response'
        "404":
          description: Todo not found
          schema:
            $ref: '#/definitions/error.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Update an existing Todo item
      tags:
      - Todo
  /user:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a list of User items, optionally filtered
        by a search query.
      parameters:
      - description: Search query to filter User items
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of User items
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Get a list of User items
      tags:
      - User
    post:
      consumes:
      - application/json
      description: This endpoint allows the user to create a new User item.
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created User item
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/error.Response'
      summary: Create a new User item
      tags:
      - User
  /user/{id}:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves a User item based on the provided ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved User item
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/error.Response'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/error.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Get a User item by ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: This endpoint allows the user to update an existing User item by
        ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated User item
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/error.Response'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/error.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.Response'
      summary: Update an existing User item
      tags:
      - User
swagger: "2.0"
